[[Main]]
  Name = "主頁"
  Pre = "home"
  #URL = "/"
  Weight = 1

[[Main]]
  Name = "關於我"
  Pre = "user"
  URL = "about.html"
   Weight = 2
  
[[Main]]
  Name = "貼文"
  Pre = "archive"
  URL = "post"
  Weight = 3

[[Main]]
  Name = "回憶錄"
  Pre = "star"
  URL = "memories"
  Weight = 4

[[Main]]
  Name = "Leetcodes "
  Pre = "code"
  URL = "leetcodes"
  Weight = 5

[[Main]]
  Name = "專案"
  Pre = "tasks"
  URL = "project"
  Weight = 6

  
[[Main]]
  Name = "成就"
  Pre = "trophy"
  URL = "achievement"
  Weight = 7

[[Main]]
  Name = "資源"
  Pre = "file"
  URL = "resources"
  Weight = 8