#--------------------------------------
# 菜单配置说明
# identifier ： 唯一标识不可重复
# name       ： 菜单显示名称
# pageref    ： 本站点链接地址，与 URL 选其一
# url        ： 站点外部链接地址，以 http 或者 https 开头
# pre        ： 菜单小图标
# weight     ： 显示顺序，字数越小越靠前
# 
# Menus Settings
# identifier : Unique ID cannot be repeated
# name       : Menu name
# pageref    : Link of webiste and not appeare same time with url
# url        : Exteneral link out of website and start with http or https
# pre        : Icon of menu
# weight     : Order number and smaller is top
# -------------------------------------
main:
  - identifier: home
    name: Home 首頁
    pageref: /
    pre: home
    weight: 1
  - identifier: categories
    name: Menu 目錄
    pageref: /categories
    pre: list
    weight: 2
  - identifier: about
    name: About 關於
    pageref: /about.html
    pre: user
    weight: 3
  - identifier: post
    name: Archive 歸檔
    pageref: /post
    pre: archive
    weight: 4
  - identifier: memories
    name: Memories 回憶
    url: /memories
    pre: star
    weight: 5
  - identifier: leetcodes
    name: Leetcodes 力扣
    url: /leetcodes
    pre: code
    weight: 6
  - identifier: project
    name: Project 專案
    url: /project
    pre: tasks
    weight: 7
  # - identifier: english
  #   name: English 英文
  #   url: /english
  #   pre: language
  #   weight: 7
  # - identifier: books
  #   name: Reading 閱讀區
  #   url: /books
  #   pre: book
  #   weight: 8
  - identifier: achievement
    name: Achievement 成就
    url: /achievement
    pre: trophy
    weight: 9
  - identifier: resources
    name: Resources 資源
    url: /resources
    pre: file
    weight: 10