#--------------------------------------
# 菜单配置说明
# identifier ： 唯一标识不可重复
# name       ： 菜单显示名称
# pageref    ： 本站点链接地址，与 URL 选其一
# url        ： 站点外部链接地址，以 http 或者 https 开头
# pre        ： 菜单小图标
# weight     ： 显示顺序，字数越小越靠前
# 
# Menus Settings
# identifier : Unique ID cannot be repeated
# name       : Menu name
# pageref    : Link of webiste and not appeare same time with url
# url        : Exteneral link out of website and start with http or https
# pre        : Icon of menu
# weight     : Order number and smaller is top
# -------------------------------------
main:
  - identifier: home
    name: 首頁
    pageref: /
    pre: home
    weight: 1
  - identifier: about
    name: 關於
    pageref: /about.html
    pre: user
    weight: 2
  - identifier: post
    name: 歸檔
    pageref: /post
    pre: archive
    weight: 3
  - identifier: memories
    name: 回憶
    url: /memories
    pre: star
    weight: 4
  - identifier: leetcodes
    name: Leetcodes
    url: /leetcodes
    pre: code
    weight: 5
  - identifier: project
    name: 專案
    url: /project
    pre: tasks
    weight: 6
  - identifier: achievement
    name: 成就
    url: /achievement
    pre: trophy
    weight: 6
  - identifier: resources
    name: 資源
    url: /resources
    pre: file
    weight: 6