[[Main]]
  Name = "Home"
  Pre = "home"
  #URL = "/"
  Weight = 1

[[Main]]
  Name = "About"
  Pre = "user"
  URL = "about.html"
   Weight = 2
  
[[Main]]
  Name = "Posts"
  Pre = "archive"
  URL = "post"
  Weight = 3

[[Main]]
  Name = "Leetcodes "
  Pre = "code"
  URL = "leetcodes"
  Weight = 4

[[Main]]
  Name = "Notes"
  Pre = "sticky-note-o"
  URL = "notes"
  Weight = 5

[[Main]]
  Name = "Projects"
  Pre = "tasks"
  URL = "project"
  Weight = 6

  
[[Main]]
  Name = "achievement"
  Pre = "trophy"
  URL = "achievement"
  Weight = 6