[[Main]]
  Name = "Home"
  Pre = "home"
  #URL = "/"
  Weight = 1
[[Main]]
  Name = "Posts"
  Pre = "archive"
  URL = "post"
  Weight = 2
[[Main]]
  Name = "About"
  Pre = "user"
  URL = "about.html"
  
[[Main]]
  Name = "Projects"
  Pre = "code"
  URL = "project"
  Weight = 3
