[TagsCloud]
  Enable = true
  Limit = 20

[Share]
  Enable = false
  AddthisId = "Your AddthisId"

[Comment]
  Enable = true
  Module = "Waline"
  LiveReId = "jackson.tmm"
  WalineSerURL = "https://blogger-chat-server.vercel.app/"

  # If Module is "Utterances",see https://utteranc.es/
  UtterancesRepo = "owner/repo"
  UtterancesTheme = "github-light"
  UtterancesTitle = "pathname"

[LeanCloud]
 AppId = "JyrUwPHC7QNF67JQSvMaF3Dv-MdYXbMMI"
 AppKey = "Uub02Q0GnVDepc8vmgqRavmr"
 ServerURL = "https://blogger-chat-server.vercel.app/"

[Statis]
  BusuanziCounter = false
#  CNNZSiteId = "Your CNNZSiteId"
#  BaiduSiteId = "Your BaiduSiteId"
#  GoogleSiteId = "Your GoogleSiteId"

[OnlineIM]
  Enable = false
  DaoVoiceId = "Your DaoVoiceId"

[Others]
#  RevolverMapId = "Your RevolverMapId"