[[Main]]
  Name = "Home"
  Pre = "home"
  #URL = "/"
  Weight = 1

[[Main]]
  Name = "About"
  Pre = "user"
  URL = "about.html"
   Weight = 2
  
[[Main]]
  Name = "Posts"
  Pre = "archive"
  URL = "post"
  Weight = 3

# [[Main]]
#   Name = "Memories"
#   Pre = "star"
#   URL = "memories"
#   Weight = 4

[[Main]]
  Name = "Leetcodes "
  Pre = "code"
  URL = "leetcodes"
  Weight = 5

[[Main]]
  Name = "Projects"
  Pre = "tasks"
  URL = "project"
  Weight = 6

  
[[Main]]
  Name = "achievement"
  Pre = "trophy"
  URL = "achievement"
  Weight = 7

# [[Main]]
#   Name = "resources"
#   Pre = "file"
#   URL = "resources"
#   Weight = 8